spring.application.name=ofertas
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/ofertas_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

usuarios-service.url=http://localhost:8081/api/usuarios
subastas-service.url=http://localhost:8083/api/subastas

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/